
Onager - Build
==============================================================================

** Introduction
This will describe how to build Onger by yourself on a GNU Linux System.
Parts may also work on BSD or even other Unix systems. As the tools have been
ported you can also build this under Cygwin (but upgrading to Linux is the
better choice...).

** What you need
You need the following packages:
 - prc-tools  http://prc-tools.sf.net
 - pilrc      http://www.ardiri.com/palm/pilrc/
 - GNU sed    http://www.gnu.org/software/sed/sed.html
 - GNU awk    http://www.gnu.org/software/gawk/gawk.html
 - GNU tar    http://www.gnu.org/software/tar/tar.html
 - GNU Make   http://www.gnu.org/software/make/make.html

Sed, awk, tar and make are installed on most Linux systems anyway. If you
use RedHat you can get RPMs for prc-tools from their webpage. For pilrc
try http://www.rpmfind.net/linux/rpm2html/search.php?query=pilrc

** Compiling Onager
If the tools are all in place the building is as simple as typing "make".
Hmm, wait it is just typing make...
I have also implemented the usual targets as clean, all etc.
To build a different language use
LANGUAGE=language make clean all
where language is one of the language names listed in the languages file.



Tim Niemueller <tim@niemueller.de>
Rees, September 16th 2003


$Id: BUILD,v 1.1 2003/09/16 17:32:51 tim Exp $
